version: "3.8"

services:
  db:
    container_name: myscheduler-db
    image: postgres:13-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    networks:
      - myscheduler

  app:
    container_name: my-scheduler
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/home/docker
    ports:
      - 8000:8000
    command: scripts/start.sh
    depends_on:
      - db
    networks:
      - myscheduler

networks:
  myscheduler:
