# Generated by Django 3.2.3 on 2021-05-22 15:18

from django.db import migrations, models
import myscheduler.applications.authentication.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('cpf_validation_status', models.CharField(choices=[('pending', 'Pending'), ('invalid', 'Invalid'), ('valid', 'Valid')], default='pending', max_length=7, verbose_name='cpf validation status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='has subscribed')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
            managers=[
                ('objects', myscheduler.applications.authentication.managers.PersonManager()),
            ],
        ),
    ]
